name: My first workflow
on : push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@main   
        - name: Welcome message
          run: echo "My first successfull github actions"
        - name: List files
          run: ls
        - name: Read files
          run: cat README.md

